export const predefinedAnswers = {
    "qual seu nome?": "Eu sou o FúriaBot!",
    "quem é o melhor time?": "FURIA, é claro!",
    "olá": "Oi! Como posso ajudar?",
    "oi": "Olá! Como você está?",
    "oi tudo bem?": "Olá! Como você está?",
    "bom dia": "Bom dia! Como posso te ajudar hoje?",
    "boa tarde": "Boa tarde! O que posso fazer por você?",
    "boa noite": "Boa noite! Precisa de alguma ajuda?",
    "site da furia": "Para saber mais sobre a FURIA e ficar por dentro das últimas novidades, acesse nosso site oficial: https://www.furia.gg.",
    "quem são os jogadores da FURIA?": "A equipe de CS:GO da FURIA inclui FalleN, yuurih, KSCERATO, molodoy e YEKINDAR.",
    "quais conquistas da furia?": "A FURIA é uma organização com diversas conquistas em diferentes jogos eletrônicos. As principais incluem:\n\n- ESL Pro League Season 12: North America: 1º lugar\n- IEM Rio Major 2022: Semifinalista (3º-4º lugar)\n- ESL Pro League Season 13: 3º-4º lugar\n- ESL Pro League Season 15: 3º-4º lugar\n- IEM Rio 2024: 3º-4º lugar\n- Arctic Invitational 2019: 1º lugar\n- Diversas outras colocações de destaque em campeonatos importantes.",
    "quando a furia joga?": "A próxima partida da FURIA no Counter-Strike será no PGL Astana 2025, que começa no dia 10 de maio de 2025.",
    "quais foram as últimas partidas da furia?": "09 de abril de 2025: FURIA 0 - 2 The Mongolz (PGL Bucharest 2025)\n08 de abril de 2025: FURIA 0 - 2 Virtus.pro (PGL Bucharest 2025)\n06 de abril de 2025: FURIA 1 - 2 Complexity (PGL Bucharest 2025)\n22 de março de 2025: FURIA 2 - 0 Apogee (BLAST Open Spring 2025)\n20 de março de 2025: NaVi 2 - 0 FURIA (ESL Pro League Season 21)",
    "que ano foi fundado a furia?": "A PANTERA foi fundada em agosto de 2017.",
    "qual a história da furia?": "A FURIA, fundada em 2017 em Uberlândia por Jaime Pádua, André Akkari e Cris Guedes, surgiu com foco no CS:GO, rapidamente ascendendo no cenário brasileiro e mundial, chegando ao top 3 do ranking da HLTV. A organização expandiu-se para outros esports como Rocket League (com destaque no mundial de 2022), Valorant, League of Legends, Rainbow Six Siege e Apex Legends. Mais recentemente, em 2025, anunciou equipes de Futebol de 7 (com Neymar na presidência) e Porsche Cup Brasil. A FURIA conquistou títulos importantes, foi premiada como a melhor organização de esports no Brasil em 2020 e 2021 e reconhecida internacionalmente. Hoje, é uma das maiores e mais populares organizações do Brasil, com um time feminino de CS2 que fez história, representando garra e ambição no cenário global de esports.",
    "qual a função do yuurih?": "yuurih é Rifler e é conhecido por sua habilidade em controlar o mapa e por sua versatilidade nas partidas.",
    "qual a função do KSCERATO?": "KSCERATO é Rifler e é reconhecido como um dos jogadores mais consistentes da FURIA, com uma habilidade impressionante de posicionamento e mecânica.",
    "qual a função do FalleN?": "FalleN é In-game Leader (IGL) e é o cérebro estratégico da FURIA, conhecido por sua liderança e estilo de jogo agressivo.",
    "qual a função do molodoy?": "molodoy é Rifler e se destaca por sua agilidade e capacidade de adaptação a diferentes situações durante os jogos.",
    "qual a função do YEKINDAR?": "YEKINDAR é Rifler e é altamente respeitado por sua habilidade mecânica e liderança dentro de jogo.",
    "quem é o FalleN?": "FalleN, nome real Gabriel Toledo, é um dos maiores jogadores da história do CS:GO. Com sua vasta experiência e inteligência tática, ele se destacou como um dos líderes mais respeitados, tanto no Brasil quanto internacionalmente. Ele ajudou a fundar a FURIA e foi fundamental para sua ascensão no cenário global.",
    "quem é o yuurih?": "yuurih, nome real Yuri 'yuurih' Santos, é um rifler brasileiro com uma habilidade técnica impressionante. Reconhecido por sua capacidade de controlar os mapas e sua versatilidade, yuurih tem sido uma peça chave na ascensão da FURIA ao topo do cenário de CS:GO.",
    "quem é o KSCERATO?": "KSCERATO, nome real Kaike 'KSCERATO' Cerato, é um dos jogadores mais consistentes da FURIA. Com sua habilidade de posicionamento e mecânica refinada, ele é considerado um dos melhores riflers do mundo, sendo uma peça fundamental no sucesso da FURIA.",
    "quem é o molodoy?": "molodoy, nome real Andrey 'molodoy' Mikhaylov, é um rifler talentoso, conhecido por sua agilidade e adaptabilidade durante as partidas. Embora novo no cenário internacional, ele se destaca como uma promessa para o futuro do CS:GO.",
    "quem é o YEKINDAR?": "YEKINDAR, nome real Mareks 'YEKINDAR' Gaļinskis, é um rifler letão, reconhecido pela sua habilidade mecânica excepcional e por sua liderança dentro de jogo. Ele se destacou rapidamente no cenário internacional e é uma peça essencial na FURIA.",
    "o que é CS:GO?": "Counter-Strike: Global Offensive (CS:GO) é um jogo de tiro em primeira pessoa que coloca duas equipes, Terroristas e Contra-Terroristas, em combate para completar objetivos. É um dos jogos mais populares de eSports.",
    "quais são as modalidades da FURIA?": "A FURIA tem equipes competindo em diversas modalidades, incluindo CS:GO, Valorant, League of Legends, Rainbow Six Siege, e mais recentemente em Futebol de 7 e Porsche Cup Brasil.",
    "quais são os principais campeonatos de CS:GO?": "Os principais campeonatos de CS:GO incluem a ESL Pro League, IEM (Intel Extreme Masters), PGL Major, BLAST Premier, e o CS:GO Major Championship.",
    "qual a diferença entre Rifler e AWPer?": "Riflers são jogadores responsáveis por controlar o mapa com armas automáticas (como a AK-47 e M4). AWPer é o jogador especializado no uso da AWP, uma arma de longo alcance que exige precisão.",
    "o que é um IGL?": "IGL significa In-Game Leader. É o jogador que lidera a equipe durante as partidas, tomando decisões estratégicas e coordenando o time.",
    "quais são os maiores rivais da FURIA no CS:GO?": "A FURIA tem grandes rivais como Astralis, NAVI, Liquid, e FaZe Clan, equipes que competem no mais alto nível mundial.",
    "quais as metas da FURIA para 2025?": "A FURIA tem como objetivo continuar seu domínio nas competições internacionais, com foco no fortalecimento de suas equipes, especialmente em CS:GO, Valorant e em expandir suas participações em outras modalidades de esports.",
    "quem é o fundador da FURIA?": "A FURIA foi fundada por Jaime Pádua, André Akkari e Cris Guedes em 2017.",
    "onde a FURIA está localizada?": "A sede da FURIA está em Uberlândia, Minas Gerais, Brasil. A organização também possui centros de treinamento em outras localidades.",
    "quem é o treinador da FURIA?": "O atual treinador da FURIA é o ex-jogador e estrategista André 'esA' Pereira, que assumiu o cargo para guiar a equipe nas competições internacionais.",
    "qual é a maior vitória da FURIA no CS:GO?": "Uma das maiores vitórias da FURIA foi a conquista da ESL Pro League Season 12: North America, onde a equipe venceu o torneio e se consolidou como uma das melhores do cenário.",
    "o que é um Major no CS:GO?": "Os Majors são torneios de CS:GO de maior prestígio, realizados anualmente e organizados pela Valve, que oferecem prêmios milionários e atraem os melhores times do mundo.",
    "qual é o maior prêmio já conquistado pela FURIA?": "A maior premiação da FURIA veio com a conquista do 1º lugar na ESL Pro League Season 12: North America, garantindo um prêmio significativo de $200.000.",
    "a FURIA já teve algum jogador feminino?": "Sim! A FURIA tem uma equipe feminina de CS2, composta por jogadoras talentosas que se destacam no cenário competitivo feminino de esports.",
    "qual é o maior rival da FURIA no Brasil?": "No Brasil, um dos maiores rivais da FURIA é a INTZ, que sempre fez parte da competição nacional em jogos como CS:GO e League of Legends.",
    "quais são os títulos da FURIA no Rocket League?": "A FURIA conquistou diversos títulos importantes no Rocket League, incluindo uma participação histórica no Mundial de 2022.",
    "quais são os planos da FURIA para expandir para outros jogos?": "A FURIA planeja expandir suas equipes para mais jogos de esports, incluindo Apex Legends, e continuar sua estratégia de diversificação nas modalidades de esports, com destaque para as equipes de Futebol de 7 e Porsche Cup Brasil.",
    "quem é você?": "Eu sou o FúriaBot, o assistente oficial da FURIA! Estou aqui para responder perguntas sobre a organização e seus jogadores.",
    "você é humano?": "Não, eu sou o FúriaBot, um assistente virtual criado para te ajudar com tudo sobre a FURIA!",
    "você é real?": "Sou um assistente virtual criado especialmente para responder perguntas sobre a FURIA e seus jogadores.",
    "o que você é?": "Sou o FúriaBot, um assistente virtual programado para fornecer informações sobre a FURIA e seus times de esports.",
    "seu nome?": "Meu nome é FúriaBot, o bot oficial da FURIA!",
    "como você se chama?": "Eu sou o FúriaBot!",
};
